#!/bin/sh -ex
version=$(curl https://api.github.com/repos/dropseed/cls/releases/latest | jq .tag_name -r)
rm -f cls_client/ffi/libs/*
echo $version > cls_client/ffi/libs/version
curl -Lf https://github.com/dropseed/cls/releases/download/$version/cls_ffi.dll -o cls_client/ffi/libs/cls_ffi.dll
curl -Lf https://github.com/dropseed/cls/releases/download/$version/libcls_ffi.dylib -o cls_client/ffi/libs/libcls_ffi.dylib
curl -Lf https://github.com/dropseed/cls/releases/download/$version/libcls_ffi_arm64.dylib -o cls_client/ffi/libs/libcls_ffi_arm64.dylib
curl -Lf https://github.com/dropseed/cls/releases/download/$version/libcls_ffi.so -o cls_client/ffi/libs/libcls_ffi.so
curl -Lf https://github.com/dropseed/cls/releases/download/$version/libcls_ffi_aarch64.so -o cls_client/ffi/libs/libcls_ffi_aarch64.so
ls -alh cls_client/ffi/libs
